hostaddress: localhost
hostport: 8888
logs:
  - name: basic
    logfile: ./test/basic.txt
  - name: break_char
    logfile: ./test/break_char.txt
    breaksymbol: ---
  - name: compressed
    logfile: ./test/compressed.txt.gz
  - name: directory
    logfile: ./test/